spring:
  datasource:
    url: jdbc:h2:mem:customer-db
  h2:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

customer:
  params:
    x: 1111
    y: 5555
