spring:
  datasource:
    url: jdbc:h2:mem:product-db
  h2:
    console:
      enabled: true

inventory:
  params:
    a: 11
    b: 22

management:
  endpoints:
    web:
      exposure:
        include: "*"