spring:
  datasource:
    url: jdbc:h2:mem:order-db
  h2:
    console:
      enabled: true

order:
  params:
    a: 11
    b: 22

management:
  endpoints:
    web:
      exposure:
        include: "*"